-- DROP TABLES IF EXIST
DROP TABLE IF EXISTS DB_BANK;
DROP TABLE IF EXISTS DB_CLIENT;
DROP TABLE IF EXISTS DB_BANK_CLIENT;
DROP TABLE IF EXISTS DB_ACCOUNT;

-- CREATE TABLES

CREATE TABLE DB_BANK (
  BANK_ID   INT PRIMARY KEY AUTO_INCREMENT,
  BANK_NAME VARCHAR(50) UNIQUE,
);

CREATE TABLE DB_CLIENT (
  CLIENT_ID                INT PRIMARY KEY AUTO_INCREMENT,
  CLIENT_NAME              VARCHAR(50),
  CLIENT_PESEL             VARCHAR(11) UNIQUE,
  CLIENT_GENDER            VARCHAR(10) NOT NULL,
  CLIENT_INITIAL_OVERDRAFT DOUBLE,
  CLIENT_EMAIL             VARCHAR(50) NOT NULL,
  CLIENT_CITY              VARCHAR(50) NOT NULL,
  CLIENT_ACTIVE_ACCOUNT_ID INT
);

CREATE TABLE DB_BANK_CLIENT (
  BANK_CLIENT_ID        INT PRIMARY KEY AUTO_INCREMENT,
  BANK_CLIENT_BANK_ID   INT,
  BANK_CLIENT_CLIENT_ID INT,
  FOREIGN KEY (BANK_CLIENT_BANK_ID) REFERENCES DB_BANK (BANK_ID) ON DELETE CASCADE,
  FOREIGN KEY (BANK_CLIENT_CLIENT_ID) REFERENCES DB_CLIENT (CLIENT_ID) ON DELETE CASCADE

);

CREATE TABLE DB_ACCOUNT (
  ACCOUNT_ID             INT PRIMARY KEY AUTO_INCREMENT,
  ACCOUNT_BANK_CLIENT_ID INT         NOT NULL,
  ACCOUNT_TYPE           VARCHAR(20) NOT NULL,
  ACCOUNT_BALANCE        DOUBLE      NOT NULL,
  ACCOUNT_OVERDRAFT      DOUBLE,
  FOREIGN KEY (ACCOUNT_BANK_CLIENT_ID) REFERENCES DB_BANK_CLIENT (BANK_CLIENT_ID) ON DELETE CASCADE
);

ALTER TABLE DB_CLIENT
  ADD FOREIGN KEY (CLIENT_ACTIVE_ACCOUNT_ID)
REFERENCES DB_ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE;

-----------------------------------------------------------------------------

-- INSERTS

INSERT INTO DB_BANK (BANK_NAME) VALUES ('Database Test Bank');


INSERT INTO DB_CLIENT (CLIENT_NAME, CLIENT_PESEL, CLIENT_GENDER, CLIENT_INITIAL_OVERDRAFT, CLIENT_EMAIL, CLIENT_CITY)
VALUES ('Tom Cruise', '78021298512', 'male', 2500, 'mymail@abc.com', 'New York');

INSERT INTO DB_CLIENT (CLIENT_NAME, CLIENT_PESEL, CLIENT_GENDER, CLIENT_INITIAL_OVERDRAFT, CLIENT_EMAIL, CLIENT_CITY)
VALUES ('Elton John', '78041298513', 'male', 0.0, 'nomail@rocks.com', 'Washington');

INSERT INTO DB_CLIENT (CLIENT_NAME, CLIENT_PESEL, CLIENT_GENDER, CLIENT_INITIAL_OVERDRAFT, CLIENT_EMAIL, CLIENT_CITY)
VALUES ('Carla Willis', '90121398512', 'female', 4000, 'jana@abc.com', 'New Jersey');

INSERT INTO DB_CLIENT (CLIENT_NAME, CLIENT_PESEL, CLIENT_GENDER, CLIENT_INITIAL_OVERDRAFT, CLIENT_EMAIL, CLIENT_CITY)
VALUES ('Leonardo Dicaprio', '92121391212', 'male', 1000, 'balti@abc.com', 'London');

INSERT INTO DB_CLIENT (CLIENT_NAME, CLIENT_PESEL, CLIENT_GENDER, CLIENT_INITIAL_OVERDRAFT, CLIENT_EMAIL, CLIENT_CITY)
VALUES ('Jena Philips', '89121398213', 'female', 500, 'mailtance@abc.com', 'London');

INSERT INTO DB_BANK_CLIENT (BANK_CLIENT_BANK_ID, BANK_CLIENT_CLIENT_ID)
VALUES (1, 1);

INSERT INTO DB_BANK_CLIENT (BANK_CLIENT_BANK_ID, BANK_CLIENT_CLIENT_ID)
VALUES (1, 2);

INSERT INTO DB_BANK_CLIENT (BANK_CLIENT_BANK_ID, BANK_CLIENT_CLIENT_ID)
VALUES (1, 3);

INSERT INTO DB_BANK_CLIENT (BANK_CLIENT_BANK_ID, BANK_CLIENT_CLIENT_ID)
VALUES (1, 4);

INSERT INTO DB_BANK_CLIENT (BANK_CLIENT_BANK_ID, BANK_CLIENT_CLIENT_ID)
VALUES (1, 5);


INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (1, 'SavingAccount', 2000, NULL);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (1, 'SavingAccount', 2000, NULL);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (2, 'SavingAccount', 1500, NULL);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (3, 'SavingAccount', 1000, NULL);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (4, 'SavingAccount', 2000, NULL);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (5, 'SavingAccount', 1500, NULL);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (1, 'CheckingAccount', 2000, 1000);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (2, 'CheckingAccount', 3000, 0);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (3, 'CheckingAccount', 2000, 150);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (4, 'CheckingAccount', -500, 1000);

INSERT INTO DB_ACCOUNT (ACCOUNT_BANK_CLIENT_ID, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_OVERDRAFT)
VALUES (5, 'CheckingAccount', 0, 7000);